name: Release

on:
  push:
    branches:
      - main

jobs:
  cdn:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.x

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: pnpm i

      - name: publish cdn
        run: pnpm cdn
        env:
          ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
          ACCESSKEYSECRET: ${{ secrets.ACCESSKEYSECRET }}

      - name: create push request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CORNERCSS }}
          commit-message: 'docs: change README CND hash'
          delete-branch: true
          branch: docs
          title: 'docs: change README CND hash'
